//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClayReporting.DataAcces
{
    using System;
    using ClayReporting.DataAcces.Modeles;
    using System.Collections.Generic;
    using System.Xml.Serialization;
    public partial class data : DataExport
    {
        /*public int id { get; set; }
        public Nullable<int> offset { get; set; }
        public Nullable<int> pressure { get; set; }
        public Nullable<int> layout { get; set; }
        public Nullable<bool> result { get; set; }
        public Nullable<int> lot { get; set; }
        public Nullable<int> timecode { get; set; }
        
        public Nullable<int> id_couleur { get; set; }
        public Nullable<int> id_etat { get; set; }
        public Nullable<int> id_composant { get; set; }
        public Nullable<int> id_etat_1 { get; set; }
    
        public virtual composant composant { get; set; }
        public virtual couleur couleur { get; set; }
        public virtual etat etat { get; set; }
        public virtual etat etat1 { get; set; }*/
        [XmlIgnore]
        public Nullable<int> id_rapport { get; set; }
        [XmlIgnore]
        public virtual rapport rapport { get; set; }

        public data() : base()
        {
            this.layout = 0;
            this.offset = 0;
            this.pressure = 0;
            this.result = false;
            this.timecode = 0;
        }
    }
}
