//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClayReporting.DataAcces
{
    using System.Xml.Serialization;
    using System;
    using System.Collections.Generic;
    [XmlRoot("datas")]
    public partial class rapport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rapport()
        {
            this.data = new List<data>();
        }
        [XmlIgnore]
        public int id { get; set; }
        //public Nullable<System.DateTime> dateTime { get; set; }
        [XmlElement("data")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<data> data { get; set; }
    }
}
